development: &development
  cluster: cluster1
  zookeeper:
    server: 127.0.0.1
    port: 2181
  base_name: openvpn
  node_name: test1
  openvpn:
    bin: vpn-watch/spec/mock/mock-openssh.rb
    port: 7500
    command:

test: &test
  <<: *development

production: &production
  <<: *development